First try at building with libcmini
Fails at
m68k-atari-mint-gcc -I../../../../libcmini/include -I../.. -m68000 -fgnu89-inline -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return -c ../av.c -o av.o
In file included from ../av.c:3:0:
/usr/lib/gcc/m68k-atari-mint/4.6.4/../../../../m68k-atari-mint/include/support.h:33:8: error: expected declaration specifiers or '...' before '(' token

because _ltoa is defined both in

libmini/include/stdlib.h
and
/usr/lib/gcc/m68k-atari-mint/4.6.4/../../../../m68k-atari-mint/include/support.h